import React from 'react';

const TermsPage = () => {
  return (
    <div className="pt-32 pb-24 bg-slate-50 min-h-screen">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 space-y-12">
        <div className="text-center space-y-4">
          <h1 className="text-4xl font-black text-primary uppercase tracking-tight">Terms of Service</h1>
          <p className="text-slate-500 font-medium text-lg">Last updated: May 19, 2026</p>
        </div>

        <div className="bg-white p-8 rounded-[24px] border border-slate-200 shadow-sm space-y-6 text-sm text-slate-600 leading-relaxed">
          <h3 className="text-lg font-bold text-primary border-b border-slate-100 pb-2 uppercase tracking-wide">1. Agreement to Terms</h3>
          <p>
            By accessing or using our platform, you agree to be bound by these Terms of Service. If you do not agree to all terms, you are prohibited from using the site.
          </p>

          <h3 className="text-lg font-bold text-primary border-b border-slate-100 pb-2 uppercase tracking-wide">2. Zoning Checker Disclaimer</h3>
          <p>
            All feasibility checks, cost estimators, and zoning results generated by the Property Checker tool are simulation calculations. Users must confirm building codes with their local city planning office before construction.
          </p>

          <h3 className="text-lg font-bold text-primary border-b border-slate-100 pb-2 uppercase tracking-wide">3. Directory Services</h3>
          <p>
            We list independent general contractors and design professionals. ADU Navi is not liable for structural performance, billing disputes, or build timeline delays arising from contracts with directory professionals.
          </p>

          <h3 className="text-lg font-bold text-primary border-b border-slate-100 pb-2 uppercase tracking-wide">4. Limitation of Liability</h3>
          <p>
            In no event shall ADU Navi be liable for any damages arising out of the use or inability to use the planning materials or zoning guides on our platform.
          </p>
        </div>
      </div>
    </div>
  );
};

export default TermsPage;
